"""test

Revision ID: 88be8c53b22a
Revises: 
Create Date: 2024-12-23 11:30:02.475935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88be8c53b22a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('creation_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('update_date', sa.Date(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('avatar', sa.String(), nullable=False),
    sa.Column('photo_preview', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('creation_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('update_date', sa.Date(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('creation_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('update_date', sa.Date(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('theme_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('header', sa.String(), nullable=True),
    sa.Column('foto_1', sa.String(), nullable=True),
    sa.Column('foto_2', sa.String(), nullable=True),
    sa.Column('foto_3', sa.String(), nullable=True),
    sa.Column('foto_4', sa.String(), nullable=True),
    sa.Column('foto_5', sa.String(), nullable=True),
    sa.Column('foto_6', sa.String(), nullable=True),
    sa.Column('foto_7', sa.String(), nullable=True),
    sa.Column('foto_8', sa.String(), nullable=True),
    sa.Column('foto_9', sa.String(), nullable=True),
    sa.Column('foto_10', sa.String(), nullable=True),
    sa.Column('foto_11', sa.String(), nullable=True),
    sa.Column('footer_bg', sa.String(), nullable=True),
    sa.Column('footer_logo', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('creation_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('update_date', sa.Date(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('author_book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('foto', sa.String(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('creation_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('update_date', sa.Date(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('constructor_book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('foto', sa.String(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('creation_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('update_date', sa.Date(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('foto_book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('foto', sa.String(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('creation_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('update_date', sa.Date(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('illustrator_book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('foto', sa.String(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('creation_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('update_date', sa.Date(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('illustrator_book')
    op.drop_table('foto_book')
    op.drop_table('constructor_book')
    op.drop_table('author_book')
    op.drop_table('theme_page')
    op.drop_table('feedback')
    op.drop_table('book')
    op.drop_table('admin')
    # ### end Alembic commands ###
